<?php
/**
 * Created by mumu.
 * Date: 2016/12/10
 * Time: 16:45
 */
namespace Wx\Controller;

class CouponController extends BaseController
{
    protected $dao;
    public function _initialize($type = false)
    {
        parent::_initialize($type); // TODO: Change the autogenerated stub
        $this->dao = M('user_coupon');
    }

    public function index(){
        $user_id = getUserId();
        $map  =[];
        $map['user_id'] = $user_id;
        $map['status'] = 1;
        $list = $this->dao->where($map)->select();
        $this->assign('list', $list);
        $this->display();
    }
}