<?php
/**
 * Created by mumu.
 * Date: 2016/12/9
 * Time: 19:50
 */
namespace Wx\Controller;
use EasyWeChat\Payment\Order;
class OrderController extends BaseController
{
    protected $dao;
    protected $order_id;
    public function _initialize($type = false)
    {
        parent::_initialize($type); // TODO: Change the autogenerated stub
        $this->dao = M('order');
    }

    public function index(){
        $list = getOrderList();
        $now = time()-10*60*60;
        foreach ($list as &$v){
            if(strtotime($v['pay_time']) < $now){
                if($v['status'] == 2){
                    $this->dao->where('id='.$v['id'])->setField('status',9);
                    $v['status'] = 9;//自动收货
                }
                if($v['status'] == 0){
                    $this->dao->where('id='.$v['id'])->setField('status',3);
                    $v['status'] = 3;//自动取消
                }
            }
        }

        $status = [0=>'待支付',1=>'等待配送',2=>'配送中',3=>'已取消',4=>'已删除',9=>'已完成'];
        $payStatus = [0=>'未支付',1=>'已支付'];
        $this->assign('status', $status);
        $this->assign('payStatus', $payStatus);
        $this->assign('list', $list);
        if(IS_AJAX){
            if($list){
                $this->ajaxReturn(toJson(true, $list));
            }
            $this->ajaxReturn(toJson('没有更多了...'));
        }
        $this->display();
    }

    public function res(){
        setWxOrder(null);
        $this->display();
    }

    public function detail(){
        $id = $_GET['id'];
        if(!$id){
            $this->error('订单号错误');
        }
        $data = $this->dao->find($id);
        if(!$data){
            $this->error('订单不存在');
        }
        $goods = M('order_goods')->where('order_id='.$id)->select();
        $address = '自提';
        if($data['is_ziti'] == 0){
            $address = M('order_address')->where('order_id='.$id)->find();
        }
        $this->assign('order', $data);
        $this->assign('goods', $goods);
        $this->assign('address', $address);
        $this->display();
    }

    function setOrder(){
        $order = [];
        $order['goods'] = $_POST['goods'];
        $order['tang'] = $_POST['tang'];
        if(!$order['goods']){
            $this->ajaxReturn(toJson('先选择一个商品再结算吧！'));
        }
        $user = getWxUser();
        $order['openid'] = $user['openid'];
        setWxOrder($order);
        $this->ajaxReturn(toJson(true));
    }

    public function delete(){
        $id = $_POST['id'];
        if(!$id){
            $this->ajaxReturn(toJson('订单ID错误'));
        }
        $res = M('order')->where('id='.$id)->setField('status', 4);
        if($res !== false){
            $this->ajaxReturn(toJson(true));
        }
        $this->ajaxReturn(toJson('删除失败'));
    }
}