<?php
/**
 * Created by mumu.
 * Date: 2016/12/10
 * Time: 14:48
 */

namespace Wx\Controller;
use EasyWeChat\Payment\Order;
class PayController extends BaseController
{
    protected $dao;
    protected $order_id;
    public function _initialize($type = false)
    {
        parent::_initialize($type); // TODO: Change the autogenerated stub
        $this->dao = M('order');
    }

    public function pay(){
        $address_id = $_POST['address'];
        $coupon_id = $_POST['coupon_id'];
        $ziti = $_POST['is_ziti'];
        if(!$address_id && !$ziti){
            $this->ajaxReturn(toJson('收货地址出错了，重新选择一下吧！'));
        }
        $order = getWxOrder();
        $order['coupon_id'] = $coupon_id;
        $order['address_id'] = $address_id;
        $order['is_ziti'] = $ziti;
        setWxOrder($order);
//        $this->ajaxReturn(toJson(json_encode($_POST)));

        $orderRes = submitWxOrder();
        if(!$orderRes){
            $this->ajaxReturn(toJson('请求订单失败!'));
        }

        //统一下单
        $attributes = [
            'trade_type'       => 'JSAPI', // JSAPI，NATIVE，APP...
            'body'             => $orderRes['body'],
            'detail'           => $orderRes['detail'],
            'out_trade_no'     => $orderRes['trade_no'],
            'total_fee'        => $orderRes['pay_total']*100,
//            'total_fee'        => 1,
            'notify_url'       => U('Notify/wx','','',$_SERVER['HTTP_HOST']), // 支付结果通知网址，如果不设置则会使用配置里的默认地址
            'openid'           => $orderRes['openid'],
        ];
        $wxOrder = new Order($attributes);
//        $this->ajaxReturn(toJson(true,$wxOrder));
        $result = $this->wechat->payment->prepare($wxOrder);
        if ($result->return_code == 'SUCCESS' && $result->result_code == 'SUCCESS'){
            $prepayId = $result->prepay_id;
        } else {
            $this->ajaxReturn(toJson($result->return_msg));
            $this->ajaxReturn(toJson('订单生成失败,请重新支付!'));
        }
        $json = $this->wechat->payment->configForPayment($prepayId);
        $this->ajaxReturn(toJson(true,$json));
    }
}