<?php
namespace Admin\Controller;
use Think\Page;

class ArticleController extends BaseController {
    protected $dao;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dao = M(CONTROLLER_NAME);
    }

    public function index(){
        $count = $this->dao->where()->count();
        $page = new \Think\Page($count,10);
        $show = $page->show();
        $list = $this->dao->where()->limit($page->firstRow.','.$page->listRows)->select();
        $this->assign("list",$list);
        $this->assign("page",$show);
        //dump($show);
        $this->display();
    }



    public function insert(){
       $data=$this->dao->create();
       $data['status']=isset($_POST['status'])?1:0;
        $data['addtime']=date("Y-m-d H:i:s", time());
       if($data){
       $result=$this->dao->add($data);
       if($result){
           $this->ajaxReturn(toJson(true));
       }
           else{

               $this->ajaxReturn(toJson("请输入指定的内容"));
           }
       }
       else{

           $this->ajaxReturn(toJson("请重新输入数据"));
       }

}
    public function edit(){
        if(isset($_GET['id'])){
            $list=$this->dao->where('id='.$_GET['id'])->find();
            $this->assign('data',$list);
           // dump($list);
            $this->display();
        }else
        {
           $data=$this->dao->create();
            $data['status']=isset($_POST['status'])?1:0;
            $data['addtime']=date("Y-m-d H:i:s", time());
            if($data){
            $result=$this->dao->where('id='.$_POST['id'])->save($data);;
            if($result){
                $this->ajaxReturn(toJson(true));
            }
            else{

                $this->ajaxReturn(toJson(true,"文章未修改或修改失败"));
            }
        }
        else{

            $this->ajaxReturn(toJson("请重新输入数据"));
        }
        }

    }
     public function del()
     {
		 if($this->dao->where()->delete($_POST['id'])){
			 $reply=M("Wx_reply");
			 $reply->where('article_id',$_POST['id'])->delete();
             $this->ajaxReturn(toJson(true));
         }
         else
             $this->ajaxReturn(toJson("删除失败"));


     }
   public function Setstatu(){
       if($this->dao->where('id='.$_POST['id'])->getField('status')==0)
         {
           $this->dao->where('id='.$_POST['id'])->setField('status',1);
           $data['data']="启用";
           $data['msg']="已启用";

           }
           else {
               $this->dao->where('id=' . $_POST['id'])->setField('status', 0);
               $data['data'] = "禁用";
               $data['msg']="已禁用";

           }
       $data['code']=200;
       $this->ajaxReturn($data);

   }
 public function shows(){

     $ar=M('Article');
     $list=$ar->where('id='.$_GET['id'])->find();
     $url="http://".$_SERVER['HTTP_HOST'].$list['pic'];
     $desc=htmlspecialchars_decode($list['desc']);
     $this->assign('desc',$desc);
     $this->assign('data',$list);
     $this->assign('img',$url);
     //dump($list);
     $this->display('');
 }











}
