<?php
/**
 * Created by mumu.
 * Date: 2016/12/13
 * Time: 11:46
 */
namespace Admin\Controller;

class OrderController extends BaseController
{
    protected $dao;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dao = M('order');
    }
    public function index(){

//        Vendor('Print.Yprint');
//        $print = new \Yprint();
//        $content = "测试测试";
//        $apiKey = "71e75ffb55bd5500a7ab21544aaac5bb8a82c000";
//        $msign = '22i4phqk4zj7';
//
//        $msg = "鲁豫食府\r\n";
//        $msg .= "********************************\r\n";
//        $msg .= "订单编号：123458678941\r\n";
//        $msg .= "下单时间：2016-05-06: 10:12:15\r\n";
//        $msg .= "********************************\r\n";
//        $msg .= "菜品名称：        数量         金额\r\n";
//        $msg .= "绝味鸭脖        1         18.00\r\n";
//        $msg .= "绝味鸭脖        1         18.00\r\n";
//        $msg .= "绝味鸭脖        1         18.00\r\n";
//        $msg .= "********************************\r\n";
//        $msg .= "总计：54.00\r\n";
//        $msg .= "********************************\r\n";
//        $msg .= "姓名：木木\r\n";
//        $msg .= "手机号：15326666666\r\n";
//        $msg .= "地址：金水东路绿地原盛国际2号楼2单元6楼603\r\n";
//        $msg .= "********************************\r\n";
//        $msg .= "<FB>客服电话:15326666666</FB>";
////打印
//        $print->action_print(4548,'4004508598',$msg,$apiKey,$msign);
//

        $map = [];
        $count = $this->dao->where($map)->count();
        $page = new \Think\Page($count,10);
        $show = $page->show();
        $list = $this->dao->where($map)->order('id DESC')->limit($page->firstRow.','.$page->listRows)->select();

        $status = [0=>'未支付',1=>'已支付',2=>'配送中',9=>'已完成'];
        $payStatus = [0=>'未支付',1=>'已支付'];
        $takeout = [0=>'',1=>'自提'];

        $this->assign('list', $list);
        $this->assign('page', $show);
        $this->assign('status', $status);
        $this->assign('payStatus', $payStatus);
        $this->assign('takeout', $takeout);
        $this->display();
    }

    public function goods(){
        $id = $_GET['id'];
        if(!$id){
            $this->error('ID错误');
        }
        $goods = M('order_goods')->where('order_id='.$id)->select();
        if(!$goods){
            $this->error('没有商品');
        }
        $good = M('goods');
        foreach ($goods as &$v){
            $g = $good->where('id='.$v['good_id'])->field('name,pic')->find();
            $v['name'] = $g['name'];
            $v['pic'] = $g['pic'];
        }
        $this->assign('list',$goods);
        $this->display();
    }

    public function printBill(){
        $id = $_GET['id'];
        if(!$id){
            $this->error('ID错误');
        }
        $order = $this->dao->field('id,trade_no,total,pay_total,discount_total,coupon_total,coupon_id,pay_time,is_ziti')->find($id);
        if(!$order){
            $this->error('订单不存在');
        }
        if($order['coupon_id']){
            $order['coupon'] = M('user_coupon')->find($order['coupon_id']);
            $order['coupon']['total'] = $order['coupon_total'];
        }
        $address = M('order_address')->where('order_id='.$id)->find();
        $order['user'] = $address['username'];
        $order['mobile'] = $address['mobile'];
        $order['address'] = $address['address'];
        $order['goods'] = M('order_goods')->where('order_id='.$id)->select();
        $this->assign('order', $order);
        $this->display();
    }

    public function setStatus(){
        $id = $_POST['id'];
        if(!$id){
            $this->ajaxReturn(toJson('ID错误'));
        }
        $res = $this->dao->where('id='.$id)->setField('status',2);
        if(false !== $res){
            $this->ajaxReturn(toJson(true));
        }
        $this->ajaxReturn(toJson('配送状态失败'));
    }

    public function printBillone(){
        $id = $_GET['id'];
        if(!$id){
            $this->error('ID错误');
        }
        $order = $this->dao->field('id,trade_no,total,pay_total,discount_total,coupon_total,coupon_id,pay_time,is_ziti')->find($id);
        if(!$order){
            $this->error('订单不存在');
        }
        if($order['coupon_id']){
            $order['coupon'] = M('user_coupon')->find($order['coupon_id']);
            $order['coupon']['total'] = $order['coupon_total'];
        }
        $address = M('order_address')->where('order_id='.$id)->find();
        $order['user'] = $address['username'];
        $order['mobile'] = $address['mobile'];
        $order['goods'] = M('order_goods')->where('order_id='.$id)->select();
        $html = '<style>body{font-size:24px;}table{max-width: 384px;}tr{font-size: 24px;}td{width: 30%;;}.right{text-align: right;}.center{text-align: center;}</style>';
        $html .= '<table>';
        $html .= '<tr style="text-align: center;"><th colspan="3">鲁豫食府</th></tr>';
        $html .= '<tr><td colspan="3">********************************</td></tr>';
        $html .= '<tr><td>订单号</td><td colspan="2" class="right">'.$order['trade_no'].'</td></tr>';
        $html .= '<tr><td>下单时间</td><td colspan="2" class="right">'.$order['pay_time'].'</td></tr>';
        $html .= '<tr><td colspan="3">********************************</td></tr>';
        $html .= '<tr><td>菜品</td><td class="center">数量</td><td class="center">金额</td></tr>';
        foreach ($order['goods'] as $v){
            $html .= '<tr><td>'.$v['good_name'].'</td><td class="center">'.$v['good_num'].'</td><td class="center">'.($v['good_price']*$v['good_num']).'</td></tr>';
        }
        $html .= '<tr><td colspan="3">********************************</td></tr>';
        if($order['is_takeout'] == 1){
            $html .= '<tr><td colspan="3">自提</td></tr>';
        } else {
            $html .= '<tr><td>姓名:</td><td colspan="2">'.$address['username'].'</td></tr>';
            $html .= '<tr><td>手机号:</td><td colspan="2">'.$address['mobile'].'</td></tr>';
            $html .= '<tr><td>地址:</td><td colspan="2">'.$address['address'].'</td></tr>';
        }
        $html .='</table>';
        $html .= '<script>setTimeout(function(){window.print();},200)</script>';
        echo $html;
    }
}