<?php
namespace Admin\Controller;
use Think\Page;
class ReplayController extends BaseController {
    protected $dao;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dao =M('Wx_reply');
    }

    public function index()
    {
        $count = $this->dao->where()->count();
        $page = new \Think\Page($count,10);
        $show = $page->show();
        $list=$this->dao->join(' luu_article ON luu_wx_reply.article_id = luu_article.id')->field('luu_wx_reply.id as rid,restatus,title,article_id,keyword')->limit($page->firstRow.','.$page->listRows)->select();
		// $list = $this->dao->where()->limit($page->firstRow.','.$page->listRows)->select();
	    //dump($list);
        $this->assign("list",$list);
        $this->assign("page",$show);
        $this->display();
    }

    public function insert(){
        $data=$this->dao->create();
        $data['restatus']=isset($_POST['restatus'])?1:0;
        if($data){
            $result=$this->dao->add($data);
            if($result){
                $this->ajaxReturn(toJson(true));
            }
            else{

                $this->ajaxReturn(toJson("请输入指定的内容"));
            }
        }
        else{

            $this->ajaxReturn(toJson("请重新输入数据"));
        }

    }
    public function edit(){

        if(isset($_GET['id'])){
            $list=$this->dao->where('id='.$_GET['id'])->find();
            $this->assign('data',$list);
            $article=M("article");
            $list2=$article->where('status',1)->order("id desc")->getField('id,title',true);
            $page = new \Think\Page(sizeof($list2),10);
            $show = $page->show();
            $list1=$article->where('status',1)->order("id desc")->limit($page->firstRow.','.$page->listRows)->getField('id,title',true);
            $this->assign("page",$show);
            $this->assign("list1",$list1);
            $this->assign("list",$list);

           $this->display();
        }else
        {
            $data=$this->dao->create();
            $data['restatus']=isset($_POST['restatus'])?1:0;
            if($data){
                $result=$this->dao->where('id='.$_POST['id'])->save($data);;
                if($result){
                    $this->ajaxReturn(toJson(true));
                }
                else{

                    $this->ajaxReturn(toJson(true,"关键词未修改或修改失败"));
                }
            }
            else{

                $this->ajaxReturn(toJson("请重新输入"));
            }
        }

    }
    public function del()
    {
        if($this->dao->delete($_POST['id'])){
            $this->ajaxReturn(toJson(true));
        }
        else
            $this->ajaxReturn(toJson("删除失败"));


    }
     public function Setstatu(){
       if($this->dao->where('id='.$_POST['id'])->getField('restatus')==0)
         {
           $this->dao->where('id='.$_POST['id'])->setField('restatus',1);
           $data['data']="启用";
           $data['msg']="已启用";

           }
           else {
               $this->dao->where('id=' . $_POST['id'])->setField('restatus', 0);
               $data['data'] = "禁用";
               $data['msg']="已禁用";

           }
       $data['code']=200;
       $this->ajaxReturn($data);

   }
    public function create(){
        $article=M("article");
        $list2=$article->where('status',1)->order("id desc")->getField('id,title',true);
        $page = new \Think\Page(sizeof($list2),10);
        $show = $page->show();
        $list1=$article->where('status',1)->order("id desc")->limit($page->firstRow.','.$page->listRows)->getField('id,title',true);
        $this->assign("page",$show);
        $this->assign("list1",$list1);
        $this->display();
    }
     public function send(){
        echo "http://".$_SERVER['HTTP_HOST'].U("Article");


     }
}
