<?php
namespace Home\Controller;
use Think\Page;
class ActivityController extends BaseController {
    protected $dao;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dao = M('Activity');
    }

    public function index(){
        $map = array();
        if($_GET){
            foreach ($_GET as $k=>$v){
                $map[$k] = $v;
            }
        }
        $count = $this->dao->where($map)->count();
        $page = new Page($count,10);
        $show = $page->show();
        $list = $this->dao->where($map)->limit($page->firstRow.','.$page->listRows)->select();
        $status = array(0=>'停止',1=>'开始');
        $type = array(1=>'折扣',2=>'满减', 3=>'立减');
        $this->assign('status', $status);
        $this->assign('type', $type);
        $this->assign('list', $list);
        $this->assign('page', $show);
        $this->display();
    }

    public function create(){
        $data = [];
        if($_GET['id']){
            $data = $this->dao->where('id='.$_GET['id'])->find();
            $data['goods_id'] = explode(',',$data['goods_id']);
        }
        $goodsMap = array();
        $goodsMap['status'] = 1;
        $goodsList = M('Goods')->where($goodsMap)->select();

        $this->assign('goodsList', $goodsList);
        $this->assign('data', $data);
        $this->display();
    }

    public function save(){
        $_POST['goods_id'] = implode(',', $_POST['goods_id']);
        if($this->dao->create()) {
            if($_POST['id']){
                if($this->dao->save() !== false){
                    $this->ajaxReturn(toJson(true));
                }
                $this->ajaxReturn(toJson('修改失败'));
            }
            if($this->dao->add()){
                $this->ajaxReturn(toJson(true));
            }
        }
        $this->ajaxReturn(toJson('添加失败'));
    }
}