<?php
/**
 * Created by mumu.
 * Date: 2016/12/6
 * Time: 17:46
 */
namespace Home\Controller;
class CategoryController extends BaseController{
    protected $dao;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dao = M('goods_category');
    }

    public function index(){
        $map = [];
        $count = $this->dao->where($map)->count();
        $page = new \Think\Page($count,10);
        $show = $page->show();
        $field = 'id,name,pid,status,sort';
        $list = $this->dao->where($map)->field($field)->order('sort DESC')->limit($page->firstRow.','.$page->listRows)->select();
        $status = [0=>'禁用',1=>'启用'];

        $this->assign('list', $list);
        $this->assign('page', $show);
        $this->assign('status', $status);
        $this->display();
    }

    public function create(){
        $pid = $_GET['pid'];
        $data = [];
        if($_GET['id']){
            $data = $this->dao->where('id='.$_GET['id'])->find();
            $pid = $data['pid'];
        }
        if($pid === 0 || $pid === '0'){
            $list = [];
        } else {
            $list = $this->dao->select();
        }

        $this->assign('data', $data);
        $this->assign('list', $list);
        $this->assign('pid', $pid);
        $this->display();
    }

    public function save(){
        if(!$_POST['is_show']){
            $_POST['is_show'] = 0;
        }
        if($this->dao->create()){

            if($_POST['id']){
                if($this->dao->save()){
                    $this->ajaxReturn(toJson(true));
                }
                $this->ajaxReturn(toJson('修改失败'));
            }
            if($this->dao->add()){
                $this->ajaxReturn(toJson(true));
            }
        }
        $this->ajaxReturn(toJson('添加失败'));
    }
}