<?php
/**
 * Created by mumu.
 * Date: 2016/12/7
 * Time: 19:09
 */
namespace Home\Controller;
class CouponController extends BaseController
{
    protected $dao;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->dao = M('Coupon');
    }

    public function index(){
        $map = [];
        $count = $this->dao->where($map)->count();
        $page = new \Think\Page($count,10);
        $show = $page->show();
        $field = 'id,name,total,min_total,begintime,endtime,num,grant_num,use_num,available_num,status';
        $list = $this->dao->where($map)->field($field)->order('id DESC')->limit($page->firstRow.','.$page->listRows)->select();
        $status = [0=>'禁用',1=>'启用'];

        $this->assign('list', $list);
        $this->assign('page', $show);
        $this->assign('status', $status);
        $this->display();
    }

    public function create(){
        $data = [];
        if($_GET['id']){
            $data = $this->dao->where('id='.$_GET['id'])->find();
            $data['goods_id'] = explode(',',$data['goods_id']);
        }
        $goodsMap = array();
        $goodsMap['status'] = 1;
        $goodsList = M('Goods')->where($goodsMap)->select();

        $this->assign('goodsList', $goodsList);
        $this->assign('data', $data);
        $this->display();
    }

    public function save(){
        $_POST['goods_id'] = implode(',', $_POST['goods_id']);
        if($this->dao->create()) {
            if($_POST['id']){
                if($this->dao->save() !== false){
                    $this->ajaxReturn(toJson(true));
                }
                $this->ajaxReturn(toJson('修改失败'));
            }
            if($this->dao->add()){
                $this->ajaxReturn(toJson(true));
            }
        }
        $this->ajaxReturn(toJson('添加失败'));
    }
}